# nightly `rustfmt` must be used for formatting.
unstable_features = true
edition = "2018"

format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_comments = true
wrap_comments = true
